universe = vanilla
executable = process.sh
arguments = $(URL)
log = log_$(Cluster).log
error = error_$(Cluster)_$(Process).err
output = output_$(Cluster)_$(Process).out
notification = Never
Requirements = (Target.HasCHTCStaging == true)
request_cpus = 1
request_memory = 3GB
request_disk = 4GB
transfer_input_files = source_code.tar.gz
should_transfer_files = YES
when_to_transfer_output = ON_EXIT


queue URL from /home/dashtiahanga/dscovr/submit/file_lists/file_list_01.txt
